name: build-main-branch
run-name: Build the project main branch
on:
  push:
    branches:
      - main
      - setup-github-actions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: |
            ALPINE_VERSION=3.19
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64, linux/arm
          push: true
          tags: quay.io/touchardv/myhome-dns:latest
